"""we test

Revision ID: a94c02e9c472
Revises: 4bab97cd5d6c
Create Date: 2023-02-22 22:40:33.101128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94c02e9c472'
down_revision = '4bab97cd5d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('post_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('post_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
